image: docker.io/ros:rolling
stages:
  - build

aleph2_common build:
  stage: build
  before_script:
  - apt update
  - rosdep update
  except:
    changes:
    - '*.nix'
  script:
  - rosdep install --from-paths . --ignore-src -y
  - colcon build
  - colcon test --return-code-on-test-failure --event-handlers desktop_notification- status- terminal_title- console_cohesion+

nix_build:
  tags: ["nix"]
  stage: build
  script:
  - nix build .#aleph2-description .#aleph2-teleop .#input-manager --verbose
  - find . -maxdepth 2  -name 'result*' -exec readlink {} \; | nix copy  --to s3://nix-continuum?endpoint=s3.uwukado.me\&region=garage\&secret-key=/var/lib/private/gitlab-runner/cache-priv-key.pem\&compression=none --verbose --stdin
nix_fmt:
  tags: ["nix"]
  stage: build
  script:
  - nix fmt -- -c .
