#!/usr/bin/env python

import rospy
from controller_manager_msgs.srv import SwitchController, SwitchControllerRequest

rospy.init_node("switch")

service_name = "aleph2/controller_manager/switch_controller"

rospy.wait_for_service(service_name)
switch_controller = rospy.ServiceProxy(service_name, SwitchController)

req = SwitchControllerRequest()

req.stop_controllers = [
    "manip/controllers/effort/base",
    "manip/controllers/effort/shoulder",
    "manip/controllers/effort/elbow",
    "manip/controllers/effort/wrist_tilt",
    "manip/controllers/effort/wrist_roll"
]

req.start_controllers = [
    "manip/controllers/position/base",
    "manip/controllers/position/shoulder",
    "manip/controllers/position/elbow",
    "manip/controllers/position/wrist_tilt",
    "manip/controllers/velocity/wrist_roll"
]

req.strictness = req.STRICT

switch_controller(req)
